import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import hero from "../../public/assets/profile/hero.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import lightBulb from "../../public/assets/svg/lightBulb.svg";
import PageTransition from "@/components/PageTransition";
import useThemeSwitcher from "@/components/hooks/useThemeSwitcher";

export default function Home() {
  const [mode, setMode] = useThemeSwitcher();

  return (
    <>
      <Head>
        <title>Jk || Dev - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition />
      <main className="flex items-center w-full min-h-[90vh]">
        <Layout className="px-8 xs:px-2">
          <div className="flex flex-row items-center justify-between w-full lg:flex-col">
            <div className="flex items-center justify-center flex-1 xs:order-1 lg:order-2">
              <Image
                src={hero}
                alt="James Kirkwood"
                className="xs:mt-[-10vh] xs:w-full md:w-7/12 lg:w-1/2 w-10/12 h-auto object-cover xs:flex grayscale-[30%] hover:grayscale-[0%] transition-all duration-700"
                priority
              />
            </div>
            <div className="flex flex-col items-center self-center flex-1 order-1 overflow-hidden lg:text-center text-black-200 dark:text-white">
              <AnimatedText
                text="Howdy! I'm James."
                className="xs:font-semibold xs:text-[11vw] sm:text-[9vw] text-[6vw] lg:justify-center w-full font-light"
              />
              <p className="mt-2 text-xl font-normal text-md xs:text-lg sm:m-0 sm:p-2 md:px-8 md:w-full xs:text-justify">
                I am a full stack developer, and my goal is to turn ideas into
                innovative web applications. Feel free to check out my latest{" "}
                {""}
                <Link
                  href="/projects"
                  className="transition-all duration-300 border-b dark:text-fifthLight text-fourth border-fourth dark:border-fifthLight"
                >
                  projects
                </Link>
                , showcasing my expertise in React.js and Web Development.
              </p>
            </div>
          </div>
        </Layout>
        <div className="absolute inline-block w-32 right-8 bottom-8">
          <Image
            onClick={() => setMode(mode === "light" ? "dark" : "light")}
            src={lightBulb}
            alt="light bulb"
            className="xs:hidden w-full h-auto hover:brightness-[120%] transition-all duration-700 cursor-pointer"
          />
        </div>
      </main>
    </>
  );
}
