import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import hero from "../../public/assets/profile/hero.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import lightBulb from "../../public/assets/svg/lightBulb.svg";
import PageTransition from "@/components/PageTransition";
import useThemeSwitcher from "@/components/hooks/useThemeSwitcher";

export default function Home() {
  const [mode, setMode] = useThemeSwitcher();

  return (
    <>
      <Head>
        <title>Jk || Dev - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition />
      <main className="flex items-center w-full min-h-[90vh]">
        <Layout className="pt-0 px-8">
          <div className="flex flex-row lg:flex-col items-center justify-between w-full">
            <div className="lg:order-2 flex-1 flex items-center justify-center">
              <Image
                src={hero}
                alt="James Kirkwood"
                className="md:w-7/12 lg:w-1/2 w-10/12 h-auto object-cover hidden xs:flex grayscale-[30%] hover:grayscale-[0%] transition-all duration-700"
                priority
              />
            </div>
            <div className="order-1 flex-1 flex lg:text-center flex-col items-center self-center overflow-hidden text-black-200 dark:text-white">
              <AnimatedText
                text="Howdy! I'm James."
                className="xs:text-[6vw] sm:text-[9vw] lg:justify-center w-full font-light"
              />
              <p className="mt-2 font-normal text-md xs:text-xl sm:m-0 sm:p-0 md:px-8 md:w-screen">
                I am a full stack developer, and my goal is to turn ideas into
                innovative web applications. Feel free to check out my latest{" "}
                {""}
                <Link
                  href="/projects"
                  className="dark:text-fifthLight text-fourth border-b border-fourth dark:border-fifthLight transition-all duration-300"
                >
                  projects
                </Link>
                , showcasing my expertise in React.js and Web Development.
              </p>
            </div>
          </div>
        </Layout>
        <div className="absolute right-8 bottom-8 inline-block w-32 ">
          <Image
            onClick={() => setMode(mode === "light" ? "dark" : "light")}
            src={lightBulb}
            alt="light bulb"
            className="hidden xs:inline-block w-full h-auto hover:brightness-[120%] transition-all duration-700 cursor-pointer"
          />
        </div>
      </main>
    </>
  );
}
